import { IBM_Plex_Sans, IBM_Plex_Mono } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";
import { Navigation } from "@/components/navigation";
import { ThemeProvider } from "@/components/theme-provider";
import { Toggle } from "@/components/toggle";


const ibmPlexSans = IBM_Plex_Sans({
  variable: "--font-ibm-plex-sans",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

const ibmPlexMono = IBM_Plex_Mono({
  variable: "--font-ibm-plex-mono",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

const recoleta = localFont({
  src: [
    {
      path: "../public/fonts/Recoleta-Light.woff2",
      weight: "300",
      style: "normal",
    },
    {
      path: "../public/fonts/Recoleta-Regular.woff2",
      weight: "400",
      style: "normal",
    },
    {
      path: "../public/fonts/Recoleta-Medium.woff2",
      weight: "500",
      style: "normal",
    },
    {
      path: "../public/fonts/Recoleta-SemiBold.woff2",
      weight: "600",
      style: "normal",
    },
    {
      path: "../public/fonts/Recoleta-Bold.woff2",
      weight: "700",
      style: "normal",
    },
    {
      path: "../public/fonts/Recoleta-Black.woff2",
      weight: "900",
      style: "normal",
    },
  ],
  variable: "--font-recoleta",
  display: "swap",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${ibmPlexSans.variable} ${ibmPlexMono.variable} ${recoleta.variable} antialiased max-w-[1440px] mx-auto overflow-y-auto no-scrollbar`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <Navigation />
          <main className=" mx-auto px-3 md:px-12">{children}</main>
        </ThemeProvider>
      </body>
    </html>
  );
}
